version: "3.9"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./docker/data/app:/root/.calorieapp

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "calorie_app"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "waqqas"
      MYSQL_USER_PASSWORD: "123456"
    ports:
      - 3306:3306
    volumes:
      - ./docker/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./docker/data/mysql:/var/lib/mysql